### ISSUE TITLE
MetaData

### ISSUE THREAD

**Issue by Most-ba** [FLUX-SE/SyliusPayumStripePlugin#68]
Hello ,
Is there a way to send metadata or custom fields then receive it back with the webhook via this plugin ?

**Comment by Prometee** [comment]
Hi @Most-ba,

Yes it's possible, decorate the DetailsProvider and you will be able to add the metadata you need : https://docs.stripe.com/metadata

**Comment by Most-ba** [comment]
> Hi @Most-ba,
> 
> Yes it's possible, decorate the DetailsProvider and you will be able to add the metadata you need : https://docs.stripe.com/metadata

Thank you for your fast replay 
Do you have and example code on how it's done? 
I've been trying for few days and it's not working 
Thank you .

**Comment by Prometee** [comment]
You simply have to understand how to decorate a service using Symfony : https://symfony.com/doc/current/service_container/service_decoration.html

```yaml
services:

    App\Stripe\Provider\DetailsProvider:
        decorates: flux_se.sylius_payum_stripe.provider.details
        arguments: ['@.inner']
```

```php
<?php

declare(strict_types=1);

namespace App\Stripe\Provider;

use Sylius\Component\Core\Model\OrderInterface;

final class DetailsProvider implements DetailsProviderInterface
{
    public function __construct(
        private DetailsProviderInterface $decorated,
    ) {
    }

    public function getDetails(OrderInterface $order): array
    {
        $details = $this->decorated->getDetails($order);
        
        // add your metadata
        
        return $details;
    }
}
```
